name: Maven Build and Nondex Test

on:
  push:
    branches:
      - nondex_action  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this to your desired Java version
          distribution: 'adopt'

      - name: Build with Maven and skip tests
        run: mvn clean install -DskipTests -pl titan-test -am

      - name: Run Nondex test
        run: mvn -pl titan-test edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.thinkaurelius.titan.graphdb.attribute.GeoshapeTest#testGeoJsonSerialization

